version: '3'
services:
  postgres:
    image: postgres:10.5-alpine
    command: postgres -c 'max_wal_size=4GB'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=graphtest
    ports:
      - "5442:5432"
